### ISSUE TITLE
[Bug]: Clicking launch game in the launcher makes LCU hang at a black screen

### ISSUE THREAD

**Issue by Fevirre** [AntoineUserName/Kestrel-Fusion-Launcher#4]
Not sure what's up but whenever i click launch game it just hangs LCU at a black screen and goes unresponsive.

**Comment by AntoineUserName** [comment]
It's a weird bug but normally it's patched the next update. What you can do now is to go to "settings" and enable "don't launch the game". So everytime you press "launch game" you just have to wait that there is writed "launching game.." and open the game manually.
